ruby '2.5.0'
source 'https://rubygems.org'

gem 'activerecord'
gem 'minitest'
gem 'mysql2'
gem 'rake'
gem 'rerun'
gem 'sinatra', '~> 2.0.0'
gem 'sinatra-activerecord'
gem 'sinatra-param', git: 'https://github.com/jonathankau/sinatra-param'
gem 'tux'
