development:
  adapter: mysql2
  encoding: utf8
  database: sinatra_boilerplate
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: sinatra_boilerplate_test
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
